#! /usr/bin/perl

use strict;

my $kill=0;
my $nline=0;
while (<>) {
  $nline++;
  die "BEGINKILL in kill section (l$nline)\n" 
    if ($kill && /BEGINKILL/);
  die "ENDKILL out of kill section (l$nline)\n" 
    if (!$kill && /ENDKILL/);

  if (/BEGINKILL/) {
      chomp;
      my $msg = $_;
      $msg =~ s/.*?BEGINKILL ?//;
      if (length ($msg) == 0) {
          $msg = "A VOUS DE JOUER";
      }
      print "\n\n//" .('/' x length($msg)). "\n// $msg\n//" .('/' x length($msg)). "\n\n";
      #print STDERR "enter kill (l$nline)\n";
      $kill = 1;
  }
  if (/ENDKILL/) {
    #print STDERR "leave kill (l$nline)\n";
    $kill = 0;
    next;
  } 
  last if /Local Variables:/;
  next if /- coding: utf-8 -/;

  print $_ unless $kill || /KILLLINE/;
}

die "End of file in kill section\n" if $kill;
